name: RO Crate to GitHub Pages
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    concurrency: ci-${{github.ref}}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build RO Crate Preview
        uses: ResearchObject/ro-crate-preview-action@v1.2.0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1            
